- name: is given number even or odd
  hosts: local
  connection: local
  vars:
    given_number: 6
  tasks:
  - when: given_number % 2 == 0
    name: is even
    debug:
      msg: "given number {{ given_number }} is even"
      
  - name: is odd
    debug: 
      msg: "given number {{ given_number }} is odd"
    when: given_number % 2 != 0
